"""Constants for the dashboard feature."""

QUICK_VIEW_ALL = "all"
QUICK_VIEW_NEEDS_REVIEW = "needs_review"
QUICK_VIEW_UNKNOWN = "unknown"
QUICK_VIEW_CATEGORIZED = "categorized"
QUICK_VIEW_CUSTOM = "custom"
QUICK_VIEW_OPTIONS = {
    QUICK_VIEW_ALL,
    QUICK_VIEW_NEEDS_REVIEW,
    QUICK_VIEW_UNKNOWN,
    QUICK_VIEW_CATEGORIZED,
    QUICK_VIEW_CUSTOM,
}
