"""Constants for the dashboard feature."""

QUICK_VIEW_ALL = "all"
QUICK_VIEW_NEEDS_REVIEW = "needs_review"
QUICK_VIEW_UNKNOWN = "unknown"
QUICK_VIEW_CATEGORIZED = "categorized"
QUICK_VIEW_CUSTOM = "custom"
QUICK_VIEW_OPTIONS = {
    QUICK_VIEW_ALL,
    QUICK_VIEW_NEEDS_REVIEW,
    QUICK_VIEW_UNKNOWN,
    QUICK_VIEW_CATEGORIZED,
    QUICK_VIEW_CUSTOM,
}
DASHBOARD_BREAKDOWN_CATEGORY = "category"
DASHBOARD_BREAKDOWN_TAG = "tag"
DASHBOARD_BREAKDOWN_OPTIONS = {
    DASHBOARD_BREAKDOWN_CATEGORY,
    DASHBOARD_BREAKDOWN_TAG,
}
DASHBOARD_TABLE_MERCHANT = "merchant"
DASHBOARD_TABLE_CATEGORY = "category"
DASHBOARD_MERCHANT_SORT_MERCHANT = "merchant"
DASHBOARD_MERCHANT_SORT_CATEGORY = "category"
DASHBOARD_MERCHANT_SORT_TRANSACTIONS = "transactions"
DASHBOARD_MERCHANT_SORT_SPENDING = "spending"
DASHBOARD_MERCHANT_SORT_PERIOD_CHANGE = "period_change"
DASHBOARD_MERCHANT_SORT_RULES = "rules"
DASHBOARD_MERCHANT_SORTS = {
    DASHBOARD_MERCHANT_SORT_MERCHANT,
    DASHBOARD_MERCHANT_SORT_CATEGORY,
    DASHBOARD_MERCHANT_SORT_TRANSACTIONS,
    DASHBOARD_MERCHANT_SORT_SPENDING,
    DASHBOARD_MERCHANT_SORT_PERIOD_CHANGE,
    DASHBOARD_MERCHANT_SORT_RULES,
}
DASHBOARD_CATEGORY_SORT_CATEGORY = "category"
DASHBOARD_CATEGORY_SORT_SPENDING = "spending"
DASHBOARD_CATEGORY_SORT_SHARE = "share"
DASHBOARD_CATEGORY_SORTS = {
    DASHBOARD_CATEGORY_SORT_CATEGORY,
    DASHBOARD_CATEGORY_SORT_SPENDING,
    DASHBOARD_CATEGORY_SORT_SHARE,
}
