"""Persistence helpers for reimbursement allocations.

The reimbursement service owns validation and orchestration. This module keeps
SQLAlchemy Core reads and writes focused on reimbursement allocation rows and
the transaction fields needed to validate links.
"""

from typing import Any

from sqlalchemy import delete, func, insert, select, update

from finance_app.core.constants import CATEGORY_SOURCE_MANUAL
from finance_app.core.money import MoneyValue, money_to_decimal
from finance_app.database.tables import categories as categories_table
from finance_app.database.tables import reimbursement_allocations as reimbursement_allocations_table
from finance_app.database.tables import reimbursement_expense_completions as expense_completions_table
from finance_app.database.tables import tags as tags_table
from finance_app.database.tables import transaction_tags as transaction_tags_table
from finance_app.database.tables import transactions as transactions_table


def inserted_primary_key(result: Any) -> int:
    """Return the integer primary key generated by a Core insert result."""
    if result.inserted_primary_key:
        return int(result.inserted_primary_key[0])
    return int(result.lastrowid)


def get_allocation(conn: Any, allocation_id: int) -> dict[str, Any] | None:
    """Return one reimbursement allocation row by id."""
    row = (
        conn.execute(
            select(
                reimbursement_allocations_table.c.id,
                reimbursement_allocations_table.c.reimbursement_transaction_id,
                reimbursement_allocations_table.c.expense_transaction_id,
                reimbursement_allocations_table.c.amount,
            ).where(reimbursement_allocations_table.c.id == allocation_id)
        )
        .mappings()
        .fetchone()
    )
    return dict(row) if row is not None else None


def get_allocation_pair(
    conn: Any, reimbursement_transaction_id: int, expense_transaction_id: int
) -> dict[str, Any] | None:
    """Return an allocation linking the supplied reimbursement and expense."""
    row = (
        conn.execute(
            select(
                reimbursement_allocations_table.c.id,
                reimbursement_allocations_table.c.reimbursement_transaction_id,
                reimbursement_allocations_table.c.expense_transaction_id,
                reimbursement_allocations_table.c.amount,
            ).where(
                reimbursement_allocations_table.c.reimbursement_transaction_id == reimbursement_transaction_id,
                reimbursement_allocations_table.c.expense_transaction_id == expense_transaction_id,
            )
        )
        .mappings()
        .fetchone()
    )
    return dict(row) if row is not None else None


def get_transaction_allocation_subject(conn: Any, transaction_id: int) -> dict[str, Any] | None:
    """Return transaction fields used by reimbursement allocation validation."""
    row = (
        conn.execute(
            select(
                transactions_table.c.id,
                transactions_table.c.tx_date,
                transactions_table.c.description,
                transactions_table.c.amount,
                transactions_table.c.category,
                transactions_table.c.category_id,
                transactions_table.c.transaction_kind,
                transactions_table.c.ignored,
                categories_table.c.builtin_key.label("category_builtin_key"),
            )
            .select_from(
                transactions_table.outerjoin(
                    categories_table,
                    categories_table.c.id == transactions_table.c.category_id,
                )
            )
            .where(transactions_table.c.id == transaction_id)
        )
        .mappings()
        .fetchone()
    )
    return dict(row) if row is not None else None


def sum_allocated_to_reimbursement(
    conn: Any,
    reimbursement_transaction_id: int,
    *,
    exclude_allocation_id: int | None = None,
) -> Any:
    """Return total amount allocated from one reimbursement credit."""
    return sum_allocations(
        conn,
        reimbursement_allocations_table.c.reimbursement_transaction_id == reimbursement_transaction_id,
        exclude_allocation_id=exclude_allocation_id,
    )


def sum_allocated_to_expense(
    conn: Any,
    expense_transaction_id: int,
    *,
    exclude_allocation_id: int | None = None,
) -> Any:
    """Return total reimbursement amount allocated to one expense."""
    return sum_allocations(
        conn,
        reimbursement_allocations_table.c.expense_transaction_id == expense_transaction_id,
        exclude_allocation_id=exclude_allocation_id,
    )


def sum_allocations(conn: Any, condition: Any, *, exclude_allocation_id: int | None = None) -> Any:
    """Return total allocation amount for a caller-supplied filter condition."""
    conditions = [condition]
    if exclude_allocation_id is not None:
        conditions.append(reimbursement_allocations_table.c.id != exclude_allocation_id)
    return conn.execute(
        select(func.coalesce(func.sum(reimbursement_allocations_table.c.amount), 0)).where(*conditions)
    ).scalar_one()


def insert_allocation(
    conn: Any,
    reimbursement_transaction_id: int,
    expense_transaction_id: int,
    amount: MoneyValue,
) -> int:
    """Insert a reimbursement allocation and return its generated id."""
    result = conn.execute(
        insert(reimbursement_allocations_table).values(
            reimbursement_transaction_id=reimbursement_transaction_id,
            expense_transaction_id=expense_transaction_id,
            amount=amount,
        )
    )
    return inserted_primary_key(result)


def update_allocation_amount(conn: Any, allocation_id: int, amount: MoneyValue) -> bool:
    """Update one reimbursement allocation amount."""
    cursor = conn.execute(
        update(reimbursement_allocations_table)
        .where(reimbursement_allocations_table.c.id == allocation_id)
        .values(amount=amount, updated_at=func.current_timestamp())
    )
    return cursor.rowcount > 0


def delete_allocation(conn: Any, allocation_id: int) -> bool:
    """Delete one reimbursement allocation."""
    cursor = conn.execute(
        delete(reimbursement_allocations_table).where(reimbursement_allocations_table.c.id == allocation_id)
    )
    return cursor.rowcount > 0


def get_expense_completion(conn: Any, expense_transaction_id: int) -> dict[str, Any] | None:
    """Return a completion marker for one reimbursable expense."""
    row = (
        conn.execute(
            select(
                expense_completions_table.c.id,
                expense_completions_table.c.expense_transaction_id,
                expense_completions_table.c.created_at,
            ).where(expense_completions_table.c.expense_transaction_id == expense_transaction_id)
        )
        .mappings()
        .fetchone()
    )
    return dict(row) if row is not None else None


def insert_expense_completion(conn: Any, expense_transaction_id: int) -> int:
    """Mark one reimbursable expense complete and return the marker id."""
    existing = get_expense_completion(conn, expense_transaction_id)
    if existing is not None:
        return int(existing["id"])
    result = conn.execute(
        insert(expense_completions_table).values(
            expense_transaction_id=expense_transaction_id,
        )
    )
    return inserted_primary_key(result)


def delete_expense_completion(conn: Any, expense_transaction_id: int) -> bool:
    """Remove the completion marker for one reimbursable expense."""
    cursor = conn.execute(
        delete(expense_completions_table).where(
            expense_completions_table.c.expense_transaction_id == expense_transaction_id
        )
    )
    return cursor.rowcount > 0


def set_transaction_tag_state(
    conn: Any,
    transaction_id: int,
    tag_name: str,
    enabled: bool,
    *,
    builtin_key: str | None = None,
) -> bool:
    """Add or remove one transaction tag while preserving other tag rows."""
    tag_id_select = select(tags_table.c.id).where(
        tags_table.c.builtin_key == builtin_key if builtin_key else tags_table.c.name == tag_name
    )
    tag_id = conn.execute(tag_id_select).scalar_one_or_none()
    if tag_id is None and builtin_key:
        tag_id = conn.execute(select(tags_table.c.id).where(tags_table.c.name == tag_name)).scalar_one_or_none()
    if tag_id is None:
        return False

    existing = (
        conn.execute(
            select(transaction_tags_table.c.tag_id).where(
                transaction_tags_table.c.transaction_id == transaction_id,
                transaction_tags_table.c.tag_id == tag_id,
            )
        )
        .mappings()
        .fetchone()
    )
    if enabled:
        if existing is not None:
            return False
        conn.execute(
            insert(transaction_tags_table).values(
                transaction_id=transaction_id,
                tag_id=tag_id,
                source=CATEGORY_SOURCE_MANUAL,
                rule_id=None,
                assigned_at=func.current_timestamp(),
            )
        )
        return True

    cursor = conn.execute(
        delete(transaction_tags_table).where(
            transaction_tags_table.c.transaction_id == transaction_id,
            transaction_tags_table.c.tag_id == tag_id,
        )
    )
    return cursor.rowcount > 0


def allocation_remaining(transaction: dict[str, Any], allocated: Any) -> Any:
    """Return remaining absolute money available on a transaction."""
    return abs(money_to_decimal(transaction["amount"])) - money_to_decimal(allocated)
